apiVersion: v1
kind: PersistentVolume
metadata:
   name: nfs
spec:
  capacity:
    storage: 90Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: woodtick.labmonkeys.tech
    path: "/data"
  mountOptions:
    - nfsvers=4.2

