---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs
spec:
  capacity:
    storage: 90Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.178.47
    path: "/data"
  mountOptions:
    - nfsvers=4.2
