---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: opennms-poc
  labels:
    app: grafana
spec:
  ports:
    - port: 3000
      name: http
  selector:
    app: grafana
  type: LoadBalancer
