---
apiVersion: v1
kind: Service
metadata:
  name: hzn-core-tcp
  namespace: opennms-poc
  labels:
    app: hzn-core
spec:
  ports:
    - port: 8980
      name: http
    - port: 8101
      name: karaf
  selector:
    app: hzn-core
  type: LoadBalancer

